import "./globals.css";
import Footer from "../Components/Home/Footer";

// const geistSans = localFont({
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });;;;;;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout=({ children })=> {
  return (
    <html lang="en">
      <body className={""}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
export default RootLayout;